src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $id_user;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $family_name;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $first_name;

    #[ORM\Column(type: 'date', nullable: true)]
    private $birth_date;

    #[ORM\Column(type: 'text', nullable: true)]
    private $adress;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Borrowing::class)]
    private $borrowings;

    #[ORM\Column(type: 'boolean')]
        private bool $is_confirmed = false;

    public function __construct()
    {
        $this->borrowings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    public function __toString(): string
    {
        return $this->email;
    }
    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function setIdUser(?int $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getFamilyName(): ?string
    {
        return $this->family_name;
    }

    public function setFamilyName(?string $family_name): self
    {
        $this->family_name = $family_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(?\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(?string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    /**
     * @return Collection|Borrowing[]
     */
    public function getBorrowings(): Collection
    {
        return $this->borrowings;
    }

    public function addBorrowing(Borrowing $borrowing): self
    {
        if (!$this->borrowings->contains($borrowing)) {
            $this->borrowings[] = $borrowing;
            $borrowing->setUser($this);
        }

        return $this;
    }

    public function removeBorrowing(Borrowing $borrowing): self
    {
        if ($this->borrowings->removeElement($borrowing)) {
            // set the owning side to null (unless already changed)
            if ($borrowing->getUser() === $this) {
                $borrowing->setUser(null);
            }
        }

        return $this;
    }

    public function getIsConfirmed(): ?bool
    {
        return $this->is_confirmed;
    }

    public function setIsConfirmed(bool $is_confirmed): self
    {
        $this->is_confirmed = $is_confirmed;

        return $this;
    }
}

src/Controller/RentalController.php
<?php

namespace App\Controller;

use App\Classe\Search;
use App\Entity\Book;
use App\Form\SearchType;
use App\Repository\BookRepository;
use App\Repository\GenreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\SerializerInterface;

class RentalController extends AbstractController
{   
    public function __construct(
        EntityManagerInterface $entityManager, 
        private ManagerRegistry $doctrine, 
        private SerializerInterface $serializer)
    {
        $this->entityManager = $entityManager;
        $this->serializer = $serializer;
    }


    #[IsGranted('ROLE_USER')]
    #[Route('/rental', name: 'rental')]   
    public function index( Request $request, BookRepository $bookRepository, PaginatorInterface $paginator, GenreRepository $genreRepository): Response
    {
        $search = new Search();
        $form = $this->createForm(SearchType::class, $search);
        $genres = $genreRepository->findAll();
        
        $form->handleRequest($request);

        //ajax response for the rental search and the checkbox
        if ($request->get("ajax")){
            $genresCheckbox = $request->get('genre');
            $books = $bookRepository->findBy(["genre" => $genresCheckbox]);

            $responses = [];

            foreach($books as $key => $book){
                $responses[$key]["id"] = $book->getId();  
            }
            
            if ($responses == []){
                $books = $bookRepository->findAll();
                $responses = [];

                foreach($books as $key => $book){
                    $responses[$key]["id"] = $book->getId(); 
                }
            }
            return new JsonResponse([
                'books' => $responses
            ]);
        }

        //Form validation 
        if ($form->isSubmitted() && $form->isValid()){
            if (isset($search)){
                $books = $bookRepository->findWithSearch($search);
            } 
        
        } else {
             //Bundle KNP pour gérer la pagination 
            $books = $this->entityManager->getRepository(Book::class)->findAll();
            $books = $paginator->paginate(
                $books, /* query NOT result */
                $request->query->getInt('page', 1)/*page number*/,
                10/*limit per page*/
            );
        }

        return $this->render('rental/rental.html.twig', [
            'books' => $books,
            'genres' => $genres,
            'form' => $form->createView(),
        ]);
    }
    

    #[Route('/allbook', name: 'all_book', methods: ['GET'])]  
    public function fetchAllBook(SerializerInterface $serializer)
    {
        $bookAll = $this->doctrine
            ->getRepository(Book::class)
            ->findAll();
            //dd($bookAll);
        $data = $serializer->serialize($bookAll, 'json', ['groups' => "show_books"]);

        $response = new Response($data, 200, [
            'Content-Type', 'application/json'
        ]);
       
        return $response;
    }
}

templates/rental/goole.html.twig
{% extends 'base.html.twig' %}

{% block title %}google{% endblock %}

{% block body %}
{% include "navbar.html.twig" %}

{% for repo in repos %}
<ul>
  <li>Titre : {{ repo.title }}</li>
</ul>


{% endfor }
{% endblock %}

templates/rental/pagination.html.twig
{# tailwindcss Sliding pagination control implementation #}
{% if pageCount > 1 %}
    <div class="inline-block">
        <div class="flex h-12 font-medium rounded-full bg-gray-300 ">
        {% if first is defined and current != first %}
            <span class="bg-gray-300 text-blue-700 px-3 py-2 text-lg border-r border-gray-400 font-bold">
                <a href="{{ path(route, query|merge({(pageParameterName): first})) }}">&lt;&lt;</a>
            </span>
        {% endif %}

        {% if previous is defined %}
            <span class="bg-gray-300  text-blue-700 px-3 text-lg py-2 border-r border-gray-400">
                <a rel="prev" href="{{ path(route, query|merge({(pageParameterName): previous})) }}">&lt;</a>
            </span>
        {% endif %}

        {% for page in pagesInRange %}
            {% if page != current %}
                <span class="bg-gray-300  text-blue-700 px-3 py-2 text-lg border-r  border-gray-400">
                    <a href="{{ path(route, query|merge({(pageParameterName): page})) }}">{{ page }}</a>
                </span>
            {% else %}
                <span class="bg-blue-600 text-white px-3 py-2 text-lg font-bold">{{ page }}</span>
            {% endif %}
        {% endfor %}

        {% if next is defined %}
            <span class="bg-gray-300  text-blue-700 px-3 py-2 text-lg border-r border-gray-400">
                <a rel="next" href="{{ path(route, query|merge({(pageParameterName): next})) }}">&gt;</a>
            </span>
        {% endif %}

        {% if last is defined and current != last %}
            <span class="bg-gray-300  text-blue-700 px-3 py-2 text-lg border-gray-400 font-bold">
                <a href="{{ path(route, query|merge({(pageParameterName): last})) }}">&gt;&gt;</a>
            </span>
        {% endif %}
        </div>
    </div>
{% endif %}

templates/rental/rental.html.twig
{% extends 'base.html.twig' %}

{% block title %}Emprunter un livre{% endblock %}

{% block body %}
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:200,400&display=swap" rel="stylesheet">
    <style>
        .work-sans {
            font-family: 'Work Sans', sans-serif;
        }
                
        #menu-toggle:checked + #menu {
            display: block;
        }
        
        .hover\:grow {
            transition: all 0.3s;
            transform: scale(1);
        }
        
        .hover\:grow:hover {
            transform: scale(1.02);
        }
    </style>
</head>

   {% include 'navbar.html.twig' %}

    {% if app.user.isConfirmed == false %}
   <div class="flex w-full items-center flex justify-center items-center py-12 px-6">
            <div>
                <div class="max-w-xs h-64 flex flex-col justify-between bg-white dark:bg-gray-800 rounded-lg border border-gray-400 mb-6 py-5 px-4">
                    <div>
                        <h4 tabindex="0" class="focus:outline-none text-gray-800 dark:text-gray-100 font-bold mb-3">Un peu de patience ! </h4>
                        <p tabindex="0" class="focus:outline-none text-gray-800 dark:text-gray-100 text-sm">Votre compte n'a pas encore été activé</p>
                    </div>
                    <div> 
                        <div class="flex items-center justify-between text-gray-800">
                            <p tabindex="0" class="focus:outline-none text-sm dark:text-gray-100">March 28, 2020</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
  
 {% elseif app.user.isConfirmed == true %}
    <section class="bg-gray-200 py-8">
        <div class="justify-center container mx-auto flex items-center flex-wrap pt-4 pb-12">
            <nav id="store" class="w-full z-30 top-0 px-6 py-1">
                <div class="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 px-2 py-3">
                    <a class="uppercase tracking-wide no-underline hover:no-underline font-bold text-gray-800 text-xl " href="#">
				    Store
			        </a>


                {{ form_start(form, {"attr":{ "id": "filter" }}) }}
                    <div class="flex items-center search-box" id="store-nav-content">
                      {{ form_row(form.string)}}
                       <div class="form-check">
                            {% for genre in genres %}
                                <input class="form-check-input appearance-none h-4 w-4 border border-gray-300 
                                              rounded-sm bg-white checked:bg-blue-600 checked:border-blue-600 
                                              focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat
                                              bg-center bg-contain  cursor-pointer" 
                                       type="checkbox" 
                                       name="genre[]" 
                                       id="genre{{ genre.id }}" 
                                       value="{{genre.id}}">
                                <label class="form-check-label inline-block text-gray-800" 
                                       for="genre{{ genre.id }}">{{ genre.name }}</label>
                            {% endfor %}
                       </div>
                       {{ form_rest(form) }}
                    </div>
                {{ form_end(form) }}
              </div>
            </nav>


            
            <div id="books" class="inline-flex">
                {% for book in books %}
                    <div class="w-full md:w-1/3 xl:w-1/4 p-6 flex flex-col text-center">
                        <a href="#">
                            <img class="hover:grow hover:shadow-lg max-h-44 mx-auto" src="{{ vich_uploader_asset(book, 'imageFile') }}">
                            <div class="pt-3 flex items-center justify-center">
                                <p class="text-xl mb-2 font-bold h-9 ">{{ book.title }}</p>
                            </div>
                                <p class="text-description pt-1 text-gray-700 text-base">{{ book.Description }}</p>
                        </a>
                            
                        {% if book.isReserved == true %}
                        <button 
                            id="rental"
                            class="bg-transparent  text-blue-700 font-semibold 
                                py-2 px-4 border border-blue-500
                                rounded opacity-50 cursor-not-allowed">Non Disponible
                        </button>
                        {% else %}
                        
                        <button 
                            id="rental"
                            class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold 
                                hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent
                                rounded"
                                >
                                <a href="{{ path('rent_book', {'id': book.id })}}">Emprunte moi
                        </button>
                        </a>
                        {% endif %}
                        
                    </div>
                {% endfor %}   
            </div>
        </div>
    </section>
    {% endif %}

    
   


{% endblock %}
    {% block javascripts %}

        <script>
            elementsBooks = [
                {% for book in books %}
                    {   
                        "id": "{{ book.id }}", 
                        "title":  "{{ book.title }}", 
                        "description": "{{ book.description }}", 
                        "image": "{{ vich_uploader_asset(book, 'imageFile') }}",
                        'isReserved': "{{ book.isReserved }}"
                    },
                {% endfor %}
            ] 
            
        </script>
    
    
    {{ encore_entry_script_tags('searchByGenre') }}
    {% endblock %}